aws_region = "us-east-2"
ecr_repository_name = "mercadolibre-scrapper-repository"
ecr_repository_tag = "latest"
lambda_function_name = "mercadolibre-scrapper-lambda"
bucket_name = "mercadolibre-scrapper-data"